stages:
  - build
  - test

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - dist

test website:
  stage: test
  script:
    - test -f dist/ds2023-30641-tulbure-claudiu-marcel-frontend/index.html
