trigger:
- master  # Define the branch to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu agent


steps:
- script: |
    npm install
    npm run build --configuration=prod
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'

# Add additional steps for deployment here, like deploying to Azure, AWS, or a custom server.